# 服务端口
server:
  port: 8081
  servlet:
    context-path: /

# 服务名
spring:
  application:
    name: bwh_service_hospital
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.190.129:3306/bwh_hospital?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=false
    url: jdbc:mysql://192.168.137.128:3306/bwh_hospital?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # nacos服务地址
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.190.129:8848
    #设置sentinel地址
    sentinel:
      transport:
        dashboard: http://192.168.190.129:8858
  #mongodb地址
  data:
    mongodb:
      host: 192.168.190.129
      port: 27017
      database: hospital
  #rabbitmq地址
  rabbitmq:
    host: 192.168.190.129
    port: 5672
    username: guest
    password: guest

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:mapper/xml/*.xml

#开启sentinel
feign:
  sentinel:
    enabled: true





